### ISSUE TITLE
Sprint Goal #7 (16 Sep - 23 Sep 2022)

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/rfcx-guardian-android#264]
## Hardware @KritsanaMike
- [x] rfcx/guardian-hardware#53
- [x] rfcx/guardian-hardware#54

## Software @Tooseriuz
- [x] #261 
- [x] Optimize SongMeter step
  - [x] rfcx/companion-android#602
  - [x] rfcx/companion-android#598
- [x] rfcx/companion-android#594

## Quality @koonchaya
- [x] rfcx/companion-android#595
- [x] rfcx/guardian-dashboard#198
- [x] #265 

---
_Not included in the sprint goal, but still tracking..._

## Companion reliability @Tooseriuz
- [x] rfcx/companion-android#599
- [x] rfcx/companion-android#600
