### ISSUE TITLE
Sprint Goal #8 (26 Sep - 30 Sep 2022)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#269]
## Software @Tooseriuz
- [x] rfcx/companion-android#605
- [x] rfcx/companion-android#594
- [x] rfcx/rfcx-api#407
- [x] rfcx/companion-android#606
- [x] rfcx/guardian-software#266
- [x] rfcx/guardian-software#267

## Quality @koonchaya
- [x] rfcx/companion-android#595
- [x] rfcx/companion-android#596
- [x] rfcx/guardian-software#268
- [x] rfcx/companion-android#608

---
_Not included in the sprint goal, but still tracking..._

## Companion reliability @Tooseriuz

- [x] rfcx/device-api#53
