### ISSUE TITLE
Sprint Goal #9 (30 Sep - 13 Oct 2022)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#273]
## Software @Tooseriuz
- [x] rfcx/companion-android#611
- [x] rfcx/guardian-software#270
- [x] rfcx/guardian-software#271
- [x] rfcx/guardian-software#272
- [x] rfcx/guardian-hardware#55

## Quality @koonchaya
- [x] rfcx/companion-android#612
- [x] rfcx/guardian-app-android#297
- [x] rfcx/guardian-app-android#296

---
_Not included in the sprint goal, but still tracking..._

## Companion reliability @Tooseriuz

- [x] rfcx/companion-android#594
