### ISSUE TITLE
Sprint Goal #10 (14 - 27 Oct 2022)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#279]
## Software @Tooseriuz
- [x] rfcx/guardian-software#276
- [x] rfcx/companion-android#616
- [x] rfcx/guardian-app-android#298
- [x] Fix crashlytics
  - [x] rfcx/companion-android#614
  - [x] rfcx/companion-android#615
  - [x] rfcx/companion-android#617
- [x] rfcx/guardian-software#257
- [x] rfcx/guardian-software#278
- [x] rfcx/guardian-software#280

## Quality @koonchaya
- [x] rfcx/companion-android#618
- [x] rfcx/guardian-app-android#296
- [x] rfcx/guardian-app-android#297

---
_Not included in the sprint goal, but still tracking..._

## Companion reliability @Tooseriuz

- [x] rfcx/companion-android#613
