### ISSUE TITLE
Sprint Goal #11 (28 Oct - 10 Nov 2022)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#285]
## Software @Tooseriuz
- [x] Companion deployment optimization
  - [x] rfcx/companion-android#621
  - [x] rfcx/companion-android#622
  - [x] rfcx/companion-android#623
  - [x] rfcx/companion-android#624
- [x] Release App
  - [x] rfcx/companion-android#625
- [x] Documentation 
  - [x] rfcx/companion-android#626
  - [x] rfcx/guardian-software#283
- [x] rfcx/companion-android#628
- [x] rfcx/guardian-software#284

## Quality @koonchaya
- [x] rfcx/guardian-dashboard#203
- [x] rfcx/companion-android#626
- [x] rfcx/companion-android#627
- [x] rfcx/guardian-software#286

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#613
- [x] rfcx/guardian-software#257
- [x] rfcx/guardian-software#276
