### ISSUE TITLE
Sprint Goal #12 (11 - 24 Nov 2022)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#290]
## Software @Tooseriuz
- [x] rfcx/companion-android#633
- [x] rfcx/companion-android#634
- [x] rfcx/companion-android#635
- [x] rfcx/companion-android#636
- [x] rfcx/guardian-software#288

## Quality @koonchaya
- [x] rfcx/companion-android#627
- [x] rfcx/guardian-software#289

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#613
- [x] rfcx/companion-android#637
