### ISSUE TITLE
Sprint Goal #13 (25 Nov - 8 Dec)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#293]
## Software @Tooseriuz
*Last sprint*
  - [x] rfcx/companion-android#633
  - [x] rfcx/companion-android#634
  - [x] rfcx/companion-android#636

*new sprint*
- [x] rfcx/guardian-hardware#56
- [x] Release
  - [x] rfcx/guardian-software#291
  - [x] rfcx/companion-android#638
  - [x] rfcx/device-api#57
- [x] rfcx/companion-android#639
- [x] rfcx/companion-android#640

## Quality @koonchaya
- [x] rfcx/guardian-software#292
- [x] rfcx/guardian-software#289
- [x]  rfcx/guardian-monitoring#136
- [ ]  rfcx/companion-android#627

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#613
- [x] rfcx/companion-android#637
