### ISSUE TITLE
Sprint Goal #14 (9 - 22 Dec)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#296]
## Software @Tooseriuz
*Last sprint*
  - [x] rfcx/guardian-hardware#56
  - [x] rfcx/companion-android#640

*new sprint*
- [x] rfcx/companion-android#645
- [x] rfcx/guardian-software#294
- [x] rfcx/guardian-hardware#57
- [x] rfcx/guardian-software#295
- [x] rfcx/companion-android#646

## Quality @koonchaya
- [x] rfcx/guardian-software#289
- [x] rfcx/companion-android#627
- [x] rfcx/companion-android#647

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#613
- [x] rfcx/companion-android#637
- [x] rfcx/guardian-monitoring#137
