### ISSUE TITLE
Sprint Goal #15 (23 Dec - 4 Jan)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#303]
## Software @Tooseriuz
*Last sprint*
  - [x] rfcx/guardian-hardware#56
  - [x] rfcx/guardian-hardware#57

*new sprint*
- [ ] Audio Coverage
  - [x] rfcx/guardian-software#299
  - [x] rfcx/companion-android#650
- [x] rfcx/companion-android#651
- [x] rfcx/guardian-software#300
- [x] rfcx/guardian-app-android#301
- [x] rfcx/guardian-software#301

## Quality @koonchaya
- [x] rfcx/guardian-software#289
- [x] rfcx/guardian-software#302

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#613
- [x] rfcx/companion-android#637
- [x] rfcx/guardian-monitoring#137
