### ISSUE TITLE
Sprint Goal #16 (6 - 19 Jan 2023)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#304]
## Software @Tooseriuz
- [x] Audio Coverage
  - [x] rfcx/companion-android#650
- [x] rfcx/companion-android#613
- [x] rfcx/guardian-software#301

## Quality @koonchaya
- [x] rfcx/guardian-software#289
- [x] rfcx/guardian-hardware#58
- [x] rfcx/companion-android#652

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/guardian-hardware#56
- [x] rfcx/companion-android#637
- [x] rfcx/guardian-monitoring#137
