### ISSUE TITLE
Sprint Goal #17 (20 Jan - 2 Feb 2023)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#306]
## Software @Tooseriuz
- [x] rfcx/companion-android#613
  - [x] rfcx/guardian-app-android#303
  - [x] rfcx/guardian-app-android#304
  - [x] rfcx/guardian-app-android#305
  - [x] rfcx/guardian-app-android#306
  - [x] rfcx/guardian-app-android#307
- [x] rfcx/guardian-software#301
- [x] rfcx/guardian-software#307
- [x] rfcx/guardian-app-android#302

## Quality @koonchaya
- [x] rfcx/guardian-software#305
- [x] rfcx/companion-android#654
- [x] rfcx/guardian-software#289

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/guardian-hardware#56
- [x] rfcx/companion-android#637
- [x] rfcx/guardian-monitoring#137
