### ISSUE TITLE
Sprint Goal #18 (3 - 16 Feb 2023)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#313]
## Software @Tooseriuz
*old sprint*
- [x] rfcx/guardian-app-android#302

*new sprint*
- [x] rfcx/guardian-monitoring#137
- [x] rfcx/companion-android#655
- [x] rfcx/companion-android#656
- [x] rfcx/companion-android#650
- [ ] Move guardian stuff to Guardian app
  - [x] rfcx/guardian-app-android#315
  - [x] rfcx/guardian-app-android#316
  - [x] rfcx/guardian-app-android#317
  - [x] rfcx/guardian-app-android#318
- [x] rfcx/guardian-app-android#319

## Quality @koonchaya
- [x] rfcx/companion-android#657
- [x] rfcx/guardian-software#311
- [x] rfcx/guardian-software#312
- [x] rfcx/companion-android#658
- [x] rfcx/companion-android#660

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/guardian-hardware#56
- [x] rfcx/companion-android#637
- [x] rfcx/companion-android#653
