### ISSUE TITLE
Sprint Goal #19 (17 Feb - 2 Mar)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#314]
## Software @Tooseriuz
*old sprint*
- [x] rfcx/companion-android#650
- [ ] Move guardian stuff
  - [x] rfcx/guardian-app-android#316
  - [x] rfcx/guardian-app-android#317
  - [x] rfcx/guardian-app-android#318

*new sprint*
- [x] rfcx/companion-android#663
- [x] rfcx/guardian-app-android#320
- [x] rfcx/companion-android#653
- [x] rfcx/guardian-monitoring#139
- [x] rfcx/companion-android#664

## Quality @koonchaya
- [x] rfcx/companion-android#658
- [x] rfcx/companion-android#665
- [x] rfcx/companion-android#659

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/guardian-hardware#56
- [x] rfcx/companion-android#637
