### ISSUE TITLE
Sprint Goal #20 (3 - 16 Mar)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#317]
## Software @Tooseriuz
**Old sprint**
- [x] rfcx/companion-android#650

*new sprint*
- [x] rfcx/guardian-app-android#325
- [x] Archive
  - [x] rfcx/guardian-software#315
- [ ] Move Guardian stuff
  - [x] rfcx/guardian-app-android#317
  - [x] rfcx/guardian-app-android#318
  - [x] rfcx/guardian-app-android#323
  - [x] rfcx/guardian-app-android#324
- [x] Companion optimization
  - [x] rfcx/companion-android#667
  - [x] rfcx/companion-android#668
  - [x] rfcx/companion-android#669
- [x] rfcx/companion-android#663

## Quality @koonchaya
- [x] rfcx/companion-android#670
- [x] rfcx/companion-android#671
- [x] rfcx/companion-android#672
- [x] rfcx/companion-android#673

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/guardian-hardware#56
- [x] rfcx/companion-android#637
