### ISSUE TITLE
Sprint Goal #21 (17 - 31 Mar)

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/rfcx-guardian-android#319]
## Software @Tooseriuz
**Old sprint**
- [x] rfcx/companion-android#650
- [x] rfcx/companion-android#663

*new sprint*
- [x] rfcx/guardian-software#318
- [ ] Move Guardian stuff
  - [x] rfcx/guardian-app-android#324
  - [x] rfcx/guardian-app-android#329
  - [x] rfcx/guardian-app-android#330
- [x] Guardian 4g/5g
  - [x] rfcx/guardian-hardware#60
  - [x] rfcx/guardian-hardware#61
- [x] Photo labeling
  - [x] rfcx/companion-android#680
  - [x] rfcx/device-api#68

## Quality @koonchaya
- [x] rfcx/companion-android#670
- [x] rfcx/companion-android#679
- [x] rfcx/companion-android#681

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/guardian-hardware#56
- [x] rfcx/companion-android#637
- [x] rfcx/companion-android#681
