### ISSUE TITLE
Sprint Goal #22 (31 Mar - 14 Apr)

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/rfcx-guardian-android#322]
## Software @Tooseriuz
- [x] rfcx/guardian-software#320
- [x] rfcx/guardian-hardware#56
- [x] Companion
  - [x] rfcx/companion-android#663
  - [x] rfcx/companion-android#683
  - [x] rfcx/companion-android#682
- [x] rfcx/guardian-software#321
- [ ] Move Guardian stuff
  - [x] rfcx/guardian-app-android#329
  - [x] rfcx/guardian-app-android#330
- [x] rfcx/guardian-hardware#62

## Quality @koonchaya
- [x] rfcx/companion-android#670
- [x] rfcx/guardian-software#289

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [x] rfcx/companion-android#681
