### ISSUE TITLE
Sprint goal#23 (17-28 Apr)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#324]
## Software @Tooseriuz
- [x] Guardian software
  - [x] rfcx/guardian-hardware#63
  - [x] rfcx/guardian-software#325
- [x] Guardian
  - [x] rfcx/guardian-hardware#56
  - [x] rfcx/guardian-software#323
- [ ] Companion
  - [x] rfcx/companion-android#663
- [ ] Move Guardian stuff
  - [x] rfcx/guardian-app-android#330
  - [x] rfcx/guardian-app-android#332
  - [x] rfcx/guardian-app-android#334
- [ ] Other
  - [x] rfcx/guardian-hardware#65

## Quality @koonchaya
- [x] rfcx/companion-android#670
- [x] rfcx/guardian-software#326
- [x] rfcx/guardian-hardware#66
- [x] rfcx/companion-android#682

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [ ] rfcx/companion-android#681
