### ISSUE TITLE
Sprint goal#24 (1-12 May)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#328]
## Software @Tooseriuz
- [x] Move Guardian stuff
  - [x] rfcx/guardian-app-android#334
  - [x] rfcx/guardian-app-android#338
  - [x] rfcx/guardian-app-android#339
  - [x] rfcx/guardian-app-android#340
- [x] rfcx/guardian-software#327
- [x] rfcx/companion-android#689
- [x] rfcx/engineering-support#273
- [x] rfcx/companion-android#691

## Quality @koonchaya
- [x] rfcx/companion-android#670
- [x] rfcx/companion-android#692
- [x] rfcx/guardian-software#329

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [ ] rfcx/companion-android#681
