### ISSUE TITLE
Spring Goal#25 (12-25 May)

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/rfcx-guardian-android#330]
## Software 
- [ ] Companion @RatreeOchn 
  - [x] rfcx/companion-android#689
  - [x] rfcx/companion-android#695
  - [x] rfcx/companion-android#696
  - [x] rfcx/companion-android#697
- [ ] Guardian App @Tooseriuz 
  - [ ] Move Guardian deployment to Guardian App
    - [x] rfcx/guardian-app-android#345
    - [x] rfcx/guardian-app-android#346
    - [x] rfcx/guardian-app-android#347
    - [x] rfcx/guardian-app-android#348
  - [x] rfcx/guardian-app-android#349

## Quality @koonchaya 
- [x] #329 
- [x] rfcx/companion-android#692
- [x] rfcx/companion-android#698
- [x] rfcx/device-api#72

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
