### ISSUE TITLE
Spring Goal#26 (26 May - 8 June)

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/rfcx-guardian-android#331]
## Software 
- [ ] Companion @RatreeOchn 
  - [x] rfcx/companion-android#689
  - [ ] rfcx/companion-android#701
  - [x] rfcx/companion-android#696
- [ ] Guardian App @Tooseriuz 
  - [ ] Move Guardian deployment to Guardian App
    - [x] rfcx/guardian-app-android#351
    - [x] rfcx/guardian-app-android#352
    - [x] rfcx/guardian-app-android#353
    - [x] rfcx/guardian-app-android#354
    - [x] rfcx/guardian-app-android#355
- [x] Offline report @RatreeOchn @Tooseriuz 
  - [x] rfcx/guardian-app-android#356
  - [x] rfcx/guardian-dashboard#208

## Quality @koonchaya 
- [x] rfcx/companion-android#692
- [x] rfcx/companion-android#702

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637

## Not in plan @koonchaya 
- [x] rfcx/device-api#72
