### ISSUE TITLE
Sprint Goal#27 (9-22 June)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#332]
## Software 
- [ ] @RatreeOchn
  - [x] rfcx/companion-android#696
  - [x] rfcx/guardian-dashboard#209
- [ ] @Tooseriuz 
  - [x] Move Guardian deployment to Guardian App
    - [x] rfcx/guardian-app-android#355
    - [x] rfcx/guardian-app-android#357
    - [x] rfcx/guardian-app-android#358
  - [x] rfcx/engineering-support#335
  - [x] rfcx/guardian-software#333
  
## Quality @koonchaya 
- [x] rfcx/companion-android#702

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [x] rfcx/guardian-software#334

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701

## Offline report @Tooseriuz @RatreeOchn
  - [x] rfcx/guardian-app-android#359
  - [x] rfcx/guardian-app-android#360
  - [x] rfcx/guardian-api#31
  - [x] rfcx/guardian-dashboard#210
