### ISSUE TITLE
Sprint Goal#28 (23 Jun - 6 July)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#335]
## Software 
- [ ] @RatreeOchn
  - [ ] Google map 
    - [x] rfcx/companion-android#703
    - [x] rfcx/companion-android#704
    - [x] rfcx/companion-android#705
  - [x] rfcx/guardian-dashboard#209
  - [ ] Unexpected threat offline report
    - [x] rfcx/guardian-dashboard#210
 
- [ ] @Tooseriuz 
   - [x] Guardian deployment on Guardian app 
     - [x] rfcx/guardian-app-android#363
   - [ ] Unexpected threat offline report
     - [x] rfcx/guardian-app-android#359
     - [x] rfcx/guardian-app-android#360
     - [x] rfcx/guardian-api#31
   - [x] rfcx/guardian-software#336
   - [x] rfcx/device-api#74
  
## Quality @koonchaya 
- [x] rfcx/companion-android#702
- [x] rfcx/guardian-app-android#364
- [x] rfcx/guardian-hardware#67
- [x] rfcx/guardian-app-android#365

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [x] rfcx/guardian-software#334
- [x] rfcx/guardian-software#333

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701

## Offline report @Tooseriuz @RatreeOchn
  - [x] rfcx/guardian-app-android#359
  - [x] rfcx/guardian-app-android#360
  - [x] rfcx/guardian-api#31
  - [x] rfcx/guardian-dashboard#210
