### ISSUE TITLE
Sprint Goal#29 (7 Jul - 20 Jul)

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/rfcx-guardian-android#337]
## Software 
- [ ] @RatreeOchn
  - [ ] Google map 
    - [x] rfcx/companion-android#703
    - [x] rfcx/companion-android#704
    - [ ] Check update compatible from previous version
    - [x] rfcx/companion-android#705
  - [ ] Unexpected threat offline report
    - [x] rfcx/guardian-dashboard#210
 
- [ ] @Tooseriuz
   - [x] #333 
   - [x] #334 
   - [ ] Unexpected threat offline report
     - [x] rfcx/guardian-api#31
   - [x] rfcx/guardian-software#336
  
## Quality @koonchaya 
- [x] rfcx/companion-android#702
- [x] rfcx/guardian-hardware#67
- [x] rfcx/guardian-app-android#365
- [x] rfcx/guardian-app-android#366

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [x] rfcx/guardian-software#334
- [x] rfcx/guardian-software#333
- [x] rfcx/device-api#74

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701

## Offline report @Tooseriuz @RatreeOchn
  - [x] rfcx/guardian-app-android#359
  - [x] rfcx/guardian-app-android#360
  - [x] rfcx/guardian-api#31
  - [x] rfcx/guardian-dashboard#210
