### ISSUE TITLE
Sprint Goal#30 (21 Jul - 3 Aug)

### ISSUE THREAD

**Issue by koonchaya** [rfcx/rfcx-guardian-android#338]
## Software 
- [ ] @RatreeOchn
   - [x] rfcx/companion-android#705
   - [x] rfcx/companion-android#708
   - [ ] rfcx/companion-android#707
   - [x] rfcx/guardian-dashboard#213
   - [x] rfcx/companion-android#710
 
- [ ] @Tooseriuz
   - [x] #333 
   - [x] #334 
   - [x] rfcx/guardian-software#336
   - [x] rfcx/guardian-app-android#370
   - [x] rfcx/guardian-api#33
  
## Quality @koonchaya 
- [x] rfcx/guardian-app-android#369
- [x] rfcx/companion-android#709

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [x] rfcx/guardian-software#334
- [x] rfcx/device-api#74

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701
