### ISSUE TITLE
Sprint Goal#31 (4 Aug - 17 Aug)

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/rfcx-guardian-android#341]
## Software 
- [ ] @RatreeOchn
   - [ ] Arbimon recorder
     - [ ] rfcx/companion-android#714
     - [ ] rfcx/companion-android#715
     - [ ] rfcx/companion-android#716
     - [ ] rfcx/companion-android#717
   - [x] rfcx/guardian-app-android#371
 
- [ ] @Tooseriuz
   - [x] #333 
   - [x] #336
   - [ ] IoTDA
     - [x] #339 
     - [x] #340 
   - [x] rfcx/guardian-app-android#372
  
## Quality @koonchaya 
- [x] rfcx/guardian-app-android#373

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [x] rfcx/device-api#74

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701
- [ ] rfcx/companion-android#707
