### ISSUE TITLE
Sprint Goal#32 (18 Aug - 1 Sep)

### ISSUE THREAD

**Issue by RatreeOchn** [rfcx/rfcx-guardian-android#342]
## Software 
@RatreeOchn
- [ ] Arbimon recorder
  - [ ] rfcx/companion-android#714
  - [x] rfcx/companion-android#715
  - [x] rfcx/companion-android#716
  - [x] rfcx/companion-android#717
- [ ] Guardian app
  - [x] rfcx/guardian-app-android#371
  - [x] rfcx/guardian-app-android#375
- [ ] Other (Public web)
  - [x] rfcx/engineering-support#399
 
@Tooseriuz
- [x] #333
- [x] rfcx/rfcx-api#489
- [x] rfcx/guardian-opi-android-source#16
- [ ] IoTDA
  - [x] #343
  
## Quality @koonchaya 
- [x] rfcx/guardian-app-android#376

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [x] rfcx/device-api#74

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701
- [ ] rfcx/companion-android#707
