### ISSUE TITLE
Sprint Goal#33 (1 Sep - 14 Sep)

### ISSUE THREAD

**Issue by RatreeOchn** [rfcx/rfcx-guardian-android#344]
## Software 
@RatreeOchn
- [ ] Arbimon recorder
  - [ ] rfcx/arbimon-recorder-android#2
  - [ ] rfcx/arbimon-recorder-android#1
  - [ ] rfcx/arbimon-recorder-android#3
  - [ ] Login page & Select project page
     - [x] rfcx/arbimon-recorder-android#4
     - [x] rfcx/arbimon-recorder-android#5
     - [x] rfcx/arbimon-recorder-android#6

 
@Tooseriuz
- [x] #333
- [x] rfcx/guardian-app-android#379
- [x] #345
- [ ] New elephant model
  - [x] #346 
  - [x] rfcx/device-api#77
  
## Quality @koonchaya 
- [x] #347

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [x] rfcx/device-api#74

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701
- [ ] rfcx/companion-android#707
