### ISSUE TITLE
Sprint Goal#34 (15 Sep - 28 Sep)

### ISSUE THREAD

**Issue by Tooseriuz** [rfcx/rfcx-guardian-android#348]
## Software 
@RatreeOchn
- [ ] Arbimon recorder
  - [x] Login page & Select project page
     - [x] rfcx/arbimon-recorder-android#4
     - [x] rfcx/arbimon-recorder-android#5
     - [x] rfcx/arbimon-recorder-android#6
  - [x] Site and Project download
     - [x] rfcx/arbimon-recorder-android#7
     - [x] rfcx/arbimon-recorder-android#8
  - [x] rfcx/arbimon-recorder-android#9
  - [x] rfcx/arbimon-recorder-android#10
  - [x] rfcx/arbimon-recorder-android#13
 
@Tooseriuz
- [x] #349 
- [x] #345 
- [x] rfcx/guardian-app-android#381
  
## Quality @koonchaya 
- [x] rfcx/arbimon-recorder-android#12
- [x] #350 

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637
- [x] rfcx/device-api#74

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701
- [ ] rfcx/companion-android#707
