### ISSUE TITLE
Sprint Goal#35 (29 Sep - 12 Oct)

### ISSUE THREAD

**Issue by RatreeOchn** [rfcx/rfcx-guardian-android#351]
## Software 
@RatreeOchn
- [ ] Arbimon recorder
  - [ ] rfcx/arbimon-recorder-android#17
  - [ ] Improve Recordings page to new design
     - [x] rfcx/arbimon-recorder-android#15
     - [x] rfcx/arbimon-recorder-android#16
  - [x] rfcx/arbimon-recorder-android#13
  - [x] rfcx/arbimon-recorder-android#11

 
@Tooseriuz
- [x] rfcx/rfcx-api#503
- [x] #352 
- [x] Arbimon recorder
  - [x] rfcx/arbimon-recorder-android#18
  - [x] rfcx/arbimon-recorder-android#19
  - [x] rfcx/arbimon-recorder-android#20
- [x] rfcx/guardian-app-android#383
- [x] rfcx/device-api#74
  
## Quality @koonchaya 
- [x] rfcx/arbimon-recorder-android#12
- [x] #350 
- [x] rfcx/guardian-app-android#384

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701
- [ ] rfcx/companion-android#707
