### ISSUE TITLE
Sprint Goal#36 (13 Oct - 27 Oct)

### ISSUE THREAD

**Issue by RatreeOchn** [rfcx/rfcx-guardian-android#353]
## Software 
@RatreeOchn
- [ ] Arbimon recorder
  - [ ] rfcx/arbimon-recorder-android#17
  - [ ] Recording process
     - [ ] rfcx/arbimon-recorder-android#21
     - [ ] rfcx/arbimon-recorder-android#22
  - [ ] Can upload record file to Arbimon
     - [ ] rfcx/arbimon-recorder-android#23
     - [ ] rfcx/arbimon-recorder-android#24
     - [ ] rfcx/arbimon-recorder-android#25
 
@Tooseriuz
- [x] #354 
- [x] #355 
- [x] Guardian app improvements
  - [x] rfcx/guardian-app-android#385
  - [x] rfcx/guardian-app-android#386
  - [x] rfcx/guardian-app-android#387
- [ ] Arbimon recorder
  - [x] rfcx/arbimon-recorder-android#20
- [x] rfcx/device-api#74
  
## Quality @koonchaya 
- [x] rfcx/arbimon-recorder-android#12
- [ ] rfcx/arbimon-recorder-android#26

---
_Not included in the sprint goal, but still tracking..._

## Not in plan @Tooseriuz

- [x] rfcx/companion-android#637

## Not in plan @koonchaya 
- [x] rfcx/device-api#72

## Not in plan @RatreeOchn
- [ ] rfcx/companion-android#701
- [ ] rfcx/companion-android#707
